import { Domain } from '../types';

export const mockDomains: Domain[] = [
  {
    id: 'bim-modeling',
    title: 'BIM & 3D Modeling',
    description: 'Building Information Modeling and 3D digital representations',
    color: 'bg-blue-500',
    icon: '🏗️',
    topics: [
      {
        id: 'parametric-design',
        title: 'Parametric Design',
        description: 'Algorithm-driven design methodologies and tools',
        content: [
          {
            id: 'param-wiki',
            title: 'Introduction to Parametric Design',
            type: 'wiki',
            description: 'Comprehensive guide to parametric design principles',
            content: 'Parametric design is a process where the design is generated by algorithms...',
            readTime: '12 min read',
            author: 'Dr. Sarah Chen',
            publishedAt: '2024-01-15',
            tags: ['parametric', 'algorithms', 'design']
          },
          {
            id: 'param-podcast',
            title: 'The Future of Parametric Architecture',
            type: 'podcast',
            description: 'Expert discussion on emerging trends in parametric design',
            content: 'A deep dive conversation with leading architects...',
            duration: '45 min',
            author: 'Architecture Today Podcast',
            publishedAt: '2024-01-20',
            tags: ['future', 'trends', 'discussion']
          },
          {
            id: 'param-video',
            title: 'Grasshopper Tutorial: Parametric Facades',
            type: 'video',
            description: 'Step-by-step tutorial for creating parametric building facades',
            content: 'Learn how to create dynamic building facades using Grasshopper...',
            duration: '28 min',
            author: 'ArchTech Academy',
            publishedAt: '2024-01-25',
            tags: ['grasshopper', 'tutorial', 'facades']
          },
          {
            id: 'param-guide',
            title: 'Parametric Design Study Guide',
            type: 'guide',
            description: 'Essential concepts and practice exercises',
            content: 'Key learning objectives and practice exercises for mastering parametric design...',
            readTime: '8 min read',
            author: 'Prof. Michael Torres',
            publishedAt: '2024-01-30',
            tags: ['study', 'exercises', 'learning']
          }
        ]
      },
      {
        id: 'bim-workflows',
        title: 'BIM Workflows',
        description: 'Collaborative workflows and best practices in BIM',
        content: [
          {
            id: 'workflow-wiki',
            title: 'BIM Collaboration Protocols',
            type: 'wiki',
            description: 'Standard protocols for multi-disciplinary BIM collaboration',
            content: 'Effective BIM collaboration requires clear protocols and standards...',
            readTime: '15 min read',
            author: 'Dr. James Rodriguez',
            publishedAt: '2024-02-01',
            tags: ['collaboration', 'protocols', 'standards']
          },
          {
            id: 'workflow-podcast',
            title: 'BIM Implementation Challenges',
            type: 'podcast',
            description: 'Real-world experiences in BIM implementation',
            content: 'Industry leaders share their experiences with BIM adoption...',
            duration: '52 min',
            author: 'BIM Talks',
            publishedAt: '2024-02-05',
            tags: ['implementation', 'challenges', 'experience']
          },
          {
            id: 'workflow-video',
            title: 'Revit to Digital Twin Workflow',
            type: 'video',
            description: 'Complete workflow from BIM to operational digital twin',
            content: 'End-to-end process for creating operational digital twins from BIM models...',
            duration: '35 min',
            author: 'Digital Twin Solutions',
            publishedAt: '2024-02-10',
            tags: ['revit', 'workflow', 'operations']
          },
          {
            id: 'workflow-guide',
            title: 'BIM Quality Control Checklist',
            type: 'guide',
            description: 'Essential quality control measures for BIM projects',
            content: 'Comprehensive checklist for ensuring BIM model quality and accuracy...',
            readTime: '6 min read',
            author: 'Quality Assurance Institute',
            publishedAt: '2024-02-15',
            tags: ['quality', 'checklist', 'standards']
          }
        ]
      },
      {
        id: 'reality-capture',
        title: 'Reality Capture',
        description: 'Scanning and photogrammetry for existing structures',
        content: [
          {
            id: 'capture-wiki',
            title: 'LiDAR vs Photogrammetry Comparison',
            type: 'wiki',
            description: 'Technical comparison of reality capture methods',
            content: 'Understanding the differences between LiDAR and photogrammetry techniques...',
            readTime: '10 min read',
            author: 'Dr. Lisa Wang',
            publishedAt: '2024-02-20',
            tags: ['lidar', 'photogrammetry', 'comparison']
          },
          {
            id: 'capture-podcast',
            title: 'Future of Building Scanning',
            type: 'podcast',
            description: 'Emerging technologies in reality capture',
            content: 'Exploring new technologies revolutionizing building documentation...',
            duration: '38 min',
            author: 'Tech Architecture Podcast',
            publishedAt: '2024-02-25',
            tags: ['scanning', 'technology', 'future']
          },
          {
            id: 'capture-video',
            title: 'Drone Photogrammetry Techniques',
            type: 'video',
            description: 'Professional drone scanning workflows',
            content: 'Learn professional techniques for aerial photogrammetry surveys...',
            duration: '42 min',
            author: 'Aerial Survey Pro',
            publishedAt: '2024-03-01',
            tags: ['drone', 'aerial', 'techniques']
          },
          {
            id: 'capture-guide',
            title: 'Reality Capture Planning Guide',
            type: 'guide',
            description: 'Pre-project planning for successful reality capture',
            content: 'Essential planning steps for successful reality capture projects...',
            readTime: '9 min read',
            author: 'Survey Planning Institute',
            publishedAt: '2024-03-05',
            tags: ['planning', 'preparation', 'workflow']
          }
        ]
      },
      {
        id: 'model-optimization',
        title: 'Model Optimization',
        description: 'Techniques for efficient 3D model processing',
        content: [
          {
            id: 'optimization-wiki',
            title: 'Mesh Optimization Fundamentals',
            type: 'wiki',
            description: 'Core principles of 3D mesh optimization',
            content: 'Understanding mesh topology and optimization techniques for better performance...',
            readTime: '14 min read',
            author: 'Dr. Alex Kumar',
            publishedAt: '2024-03-10',
            tags: ['mesh', 'optimization', 'performance']
          },
          {
            id: 'optimization-podcast',
            title: 'Performance in Large-Scale Models',
            type: 'podcast',
            description: 'Managing performance in complex architectural models',
            content: 'Strategies for maintaining performance in large-scale digital twin models...',
            duration: '47 min',
            author: 'Performance Matters',
            publishedAt: '2024-03-15',
            tags: ['performance', 'large-scale', 'optimization']
          },
          {
            id: 'optimization-video',
            title: 'LOD Strategies for Digital Twins',
            type: 'video',
            description: 'Level of Detail implementation in digital twin models',
            content: 'Implementing effective Level of Detail strategies for optimal performance...',
            duration: '33 min',
            author: 'Model Optimization Lab',
            publishedAt: '2024-03-20',
            tags: ['lod', 'detail', 'strategy']
          },
          {
            id: 'optimization-guide',
            title: 'Model Optimization Checklist',
            type: 'guide',
            description: 'Step-by-step optimization workflow',
            content: 'Systematic approach to optimizing 3D models for digital twin applications...',
            readTime: '7 min read',
            author: 'Optimization Guild',
            publishedAt: '2024-03-25',
            tags: ['checklist', 'workflow', 'systematic']
          }
        ]
      }
    ]
  },
  {
    id: 'iot-sensors',
    title: 'IoT & Sensors',
    description: 'Internet of Things integration and sensor networks',
    color: 'bg-green-500',
    icon: '📡',
    topics: [
      {
        id: 'sensor-networks',
        title: 'Sensor Networks',
        description: 'Design and deployment of building sensor networks',
        content: [
          {
            id: 'network-wiki',
            title: 'Building Sensor Network Architecture',
            type: 'wiki',
            description: 'Comprehensive guide to sensor network design',
            content: 'Designing effective sensor networks for building monitoring and control...',
            readTime: '16 min read',
            author: 'Dr. Emily Foster',
            publishedAt: '2024-01-10',
            tags: ['sensors', 'networks', 'architecture']
          },
          {
            id: 'network-podcast',
            title: 'Smart Building Sensor Strategies',
            type: 'podcast',
            description: 'Expert insights on sensor deployment strategies',
            content: 'Leading experts discuss optimal sensor placement and configuration...',
            duration: '41 min',
            author: 'Smart Building Today',
            publishedAt: '2024-01-15',
            tags: ['smart', 'deployment', 'strategy']
          },
          {
            id: 'network-video',
            title: 'Wireless Sensor Installation Guide',
            type: 'video',
            description: 'Practical guide to wireless sensor installation',
            content: 'Step-by-step installation and configuration of wireless building sensors...',
            duration: '29 min',
            author: 'IoT Install Pro',
            publishedAt: '2024-01-20',
            tags: ['wireless', 'installation', 'configuration']
          },
          {
            id: 'network-guide',
            title: 'Sensor Network Troubleshooting',
            type: 'guide',
            description: 'Common issues and solutions for sensor networks',
            content: 'Troubleshooting guide for common sensor network problems and solutions...',
            readTime: '11 min read',
            author: 'Network Support Team',
            publishedAt: '2024-01-25',
            tags: ['troubleshooting', 'problems', 'solutions']
          }
        ]
      },
      {
        id: 'data-acquisition',
        title: 'Data Acquisition',
        description: 'Methods for collecting and processing sensor data',
        content: [
          {
            id: 'acquisition-wiki',
            title: 'Real-time Data Collection Systems',
            type: 'wiki',
            description: 'Architecture for real-time building data collection',
            content: 'Designing systems for continuous real-time data collection from building sensors...',
            readTime: '13 min read',
            author: 'Data Systems Lab',
            publishedAt: '2024-02-01',
            tags: ['real-time', 'collection', 'systems']
          },
          {
            id: 'acquisition-podcast',
            title: 'Edge Computing in Buildings',
            type: 'podcast',
            description: 'Edge computing applications for building data',
            content: 'Exploring edge computing solutions for building data processing...',
            duration: '36 min',
            author: 'Edge Computing Weekly',
            publishedAt: '2024-02-05',
            tags: ['edge', 'computing', 'processing']
          },
          {
            id: 'acquisition-video',
            title: 'MQTT Protocol for Building Data',
            type: 'video',
            description: 'Implementing MQTT for building sensor communication',
            content: 'Learn how to implement MQTT protocol for efficient sensor data transmission...',
            duration: '31 min',
            author: 'Protocol Academy',
            publishedAt: '2024-02-10',
            tags: ['mqtt', 'protocol', 'communication']
          },
          {
            id: 'acquisition-guide',
            title: 'Data Quality Assurance Framework',
            type: 'guide',
            description: 'Ensuring quality in sensor data collection',
            content: 'Framework for maintaining high quality in building sensor data collection...',
            readTime: '8 min read',
            author: 'Quality Data Institute',
            publishedAt: '2024-02-15',
            tags: ['quality', 'assurance', 'framework']
          }
        ]
      },
      {
        id: 'predictive-maintenance',
        title: 'Predictive Maintenance',
        description: 'AI-driven maintenance and system optimization',
        content: [
          {
            id: 'maintenance-wiki',
            title: 'Machine Learning for Building Systems',
            type: 'wiki',
            description: 'ML applications in building system maintenance',
            content: 'Applying machine learning techniques to predict building system failures...',
            readTime: '18 min read',
            author: 'Dr. Robert Kim',
            publishedAt: '2024-02-20',
            tags: ['machine-learning', 'prediction', 'maintenance']
          },
          {
            id: 'maintenance-podcast',
            title: 'AI in Facility Management',
            type: 'podcast',
            description: 'Artificial intelligence transforming facility operations',
            content: 'How AI is revolutionizing facility management and building operations...',
            duration: '44 min',
            author: 'AI Facilities Podcast',
            publishedAt: '2024-02-25',
            tags: ['ai', 'facilities', 'operations']
          },
          {
            id: 'maintenance-video',
            title: 'Building Anomaly Detection Systems',
            type: 'video',
            description: 'Implementing anomaly detection for building systems',
            content: 'Build and deploy anomaly detection systems for building equipment monitoring...',
            duration: '39 min',
            author: 'Anomaly Detection Lab',
            publishedAt: '2024-03-01',
            tags: ['anomaly', 'detection', 'monitoring']
          },
          {
            id: 'maintenance-guide',
            title: 'Predictive Maintenance Implementation',
            type: 'guide',
            description: 'Step-by-step guide to implementing predictive maintenance',
            content: 'Complete implementation guide for predictive maintenance programs...',
            readTime: '12 min read',
            author: 'Maintenance Excellence',
            publishedAt: '2024-03-05',
            tags: ['implementation', 'program', 'excellence']
          }
        ]
      },
      {
        id: 'energy-monitoring',
        title: 'Energy Monitoring',
        description: 'Smart energy management and optimization',
        content: [
          {
            id: 'energy-wiki',
            title: 'Smart Grid Integration for Buildings',
            type: 'wiki',
            description: 'Connecting buildings to smart grid infrastructure',
            content: 'Understanding smart grid integration and its benefits for building energy management...',
            readTime: '15 min read',
            author: 'Smart Grid Institute',
            publishedAt: '2024-03-10',
            tags: ['smart-grid', 'integration', 'energy']
          },
          {
            id: 'energy-podcast',
            title: 'Net Zero Building Technologies',
            type: 'podcast',
            description: 'Technologies enabling net zero energy buildings',
            content: 'Exploring technologies and strategies for achieving net zero energy buildings...',
            duration: '48 min',
            author: 'Net Zero Today',
            publishedAt: '2024-03-15',
            tags: ['net-zero', 'technologies', 'sustainability']
          },
          {
            id: 'energy-video',
            title: 'Energy Dashboard Development',
            type: 'video',
            description: 'Creating real-time energy monitoring dashboards',
            content: 'Learn to create comprehensive energy monitoring dashboards for buildings...',
            duration: '34 min',
            author: 'Dashboard Developer',
            publishedAt: '2024-03-20',
            tags: ['dashboard', 'monitoring', 'visualization']
          },
          {
            id: 'energy-guide',
            title: 'Energy Optimization Strategies',
            type: 'guide',
            description: 'Proven strategies for building energy optimization',
            content: 'Comprehensive guide to optimizing building energy consumption and efficiency...',
            readTime: '10 min read',
            author: 'Energy Efficiency Council',
            publishedAt: '2024-03-25',
            tags: ['optimization', 'efficiency', 'strategies']
          }
        ]
      }
    ]
  },
  {
    id: 'data-analytics',
    title: 'Data Analytics',
    description: 'Advanced analytics and machine learning for building data',
    color: 'bg-purple-500',
    icon: '📊',
    topics: [
      {
        id: 'time-series',
        title: 'Time Series Analysis',
        description: 'Analyzing temporal patterns in building data',
        content: [
          {
            id: 'timeseries-wiki',
            title: 'Time Series Fundamentals for Buildings',
            type: 'wiki',
            description: 'Core concepts of time series analysis in building contexts',
            content: 'Understanding time series analysis techniques for building data interpretation...',
            readTime: '17 min read',
            author: 'Dr. Maria Santos',
            publishedAt: '2024-01-12',
            tags: ['time-series', 'analysis', 'fundamentals']
          },
          {
            id: 'timeseries-podcast',
            title: 'Seasonal Patterns in Building Data',
            type: 'podcast',
            description: 'Understanding seasonal variations in building performance',
            content: 'Analyzing seasonal patterns and their impact on building operations...',
            duration: '42 min',
            author: 'Building Analytics Weekly',
            publishedAt: '2024-01-17',
            tags: ['seasonal', 'patterns', 'performance']
          },
          {
            id: 'timeseries-video',
            title: 'Python for Building Data Analysis',
            type: 'video',
            description: 'Using Python libraries for building data time series analysis',
            content: 'Practical Python techniques for analyzing building sensor time series data...',
            duration: '46 min',
            author: 'Python Analytics Lab',
            publishedAt: '2024-01-22',
            tags: ['python', 'libraries', 'practical']
          },
          {
            id: 'timeseries-guide',
            title: 'Time Series Visualization Best Practices',
            type: 'guide',
            description: 'Effective visualization techniques for temporal building data',
            content: 'Best practices for visualizing time series data from building systems...',
            readTime: '9 min read',
            author: 'Visualization Experts',
            publishedAt: '2024-01-27',
            tags: ['visualization', 'best-practices', 'temporal']
          }
        ]
      },
      {
        id: 'pattern-recognition',
        title: 'Pattern Recognition',
        description: 'Identifying patterns and anomalies in building behavior',
        content: [
          {
            id: 'pattern-wiki',
            title: 'Occupancy Pattern Detection',
            type: 'wiki',
            description: 'Methods for detecting and analyzing occupancy patterns',
            content: 'Advanced techniques for detecting occupancy patterns in smart buildings...',
            readTime: '14 min read',
            author: 'Occupancy Analytics Team',
            publishedAt: '2024-02-02',
            tags: ['occupancy', 'detection', 'patterns']
          },
          {
            id: 'pattern-podcast',
            title: 'Behavioral Analytics in Buildings',
            type: 'podcast',
            description: 'Understanding human behavior through building data',
            content: 'How building data reveals insights about human behavior and comfort...',
            duration: '39 min',
            author: 'Behavioral Building Science',
            publishedAt: '2024-02-07',
            tags: ['behavioral', 'analytics', 'insights']
          },
          {
            id: 'pattern-video',
            title: 'Clustering Algorithms for Building Data',
            type: 'video',
            description: 'Applying clustering techniques to building datasets',
            content: 'Learn to apply various clustering algorithms to identify building usage patterns...',
            duration: '37 min',
            author: 'Machine Learning for Buildings',
            publishedAt: '2024-02-12',
            tags: ['clustering', 'algorithms', 'usage']
          },
          {
            id: 'pattern-guide',
            title: 'Anomaly Detection Framework',
            type: 'guide',
            description: 'Building robust anomaly detection systems',
            content: 'Framework for implementing effective anomaly detection in building systems...',
            readTime: '11 min read',
            author: 'Anomaly Detection Institute',
            publishedAt: '2024-02-17',
            tags: ['framework', 'detection', 'robust']
          }
        ]
      },
      {
        id: 'predictive-modeling',
        title: 'Predictive Modeling',
        description: 'Forecasting building performance and energy consumption',
        content: [
          {
            id: 'modeling-wiki',
            title: 'Energy Consumption Forecasting',
            type: 'wiki',
            description: 'Advanced models for predicting building energy usage',
            content: 'Comprehensive guide to energy consumption forecasting methodologies...',
            readTime: '19 min read',
            author: 'Dr. Ahmed Hassan',
            publishedAt: '2024-02-22',
            tags: ['forecasting', 'energy', 'consumption']
          },
          {
            id: 'modeling-podcast',
            title: 'Deep Learning for Building Prediction',
            type: 'podcast',
            description: 'Deep learning applications in building performance prediction',
            content: 'Exploring deep learning techniques for building performance prediction...',
            duration: '51 min',
            author: 'Deep Learning Buildings',
            publishedAt: '2024-02-27',
            tags: ['deep-learning', 'prediction', 'performance']
          },
          {
            id: 'modeling-video',
            title: 'LSTM Networks for Building Data',
            type: 'video',
            description: 'Implementing LSTM networks for building time series prediction',
            content: 'Build and train LSTM networks for accurate building performance prediction...',
            duration: '43 min',
            author: 'Neural Networks Lab',
            publishedAt: '2024-03-03',
            tags: ['lstm', 'networks', 'training']
          },
          {
            id: 'modeling-guide',
            title: 'Model Validation Strategies',
            type: 'guide',
            description: 'Validating predictive models for building applications',
            content: 'Essential strategies for validating and testing building prediction models...',
            readTime: '13 min read',
            author: 'Model Validation Team',
            publishedAt: '2024-03-08',
            tags: ['validation', 'testing', 'strategies']
          }
        ]
      },
      {
        id: 'performance-metrics',
        title: 'Performance Metrics',
        description: 'KPIs and benchmarking for building performance',
        content: [
          {
            id: 'metrics-wiki',
            title: 'Building Performance Indicators',
            type: 'wiki',
            description: 'Key performance indicators for smart buildings',
            content: 'Comprehensive overview of KPIs for measuring building performance and efficiency...',
            readTime: '16 min read',
            author: 'Performance Metrics Institute',
            publishedAt: '2024-03-12',
            tags: ['kpi', 'indicators', 'efficiency']
          },
          {
            id: 'metrics-podcast',
            title: 'Benchmarking Smart Buildings',
            type: 'podcast',
            description: 'Industry benchmarks for smart building performance',
            content: 'Understanding industry benchmarks and best practices for building performance...',
            duration: '45 min',
            author: 'Building Benchmarks',
            publishedAt: '2024-03-17',
            tags: ['benchmarking', 'industry', 'best-practices']
          },
          {
            id: 'metrics-video',
            title: 'Creating Performance Dashboards',
            type: 'video',
            description: 'Building comprehensive performance monitoring dashboards',
            content: 'Design and implement effective performance dashboards for building operations...',
            duration: '38 min',
            author: 'Dashboard Design Pro',
            publishedAt: '2024-03-22',
            tags: ['dashboards', 'monitoring', 'operations']
          },
          {
            id: 'metrics-guide',
            title: 'Performance Reporting Framework',
            type: 'guide',
            description: 'Structured approach to building performance reporting',
            content: 'Framework for systematic building performance reporting and analysis...',
            readTime: '10 min read',
            author: 'Reporting Standards Group',
            publishedAt: '2024-03-27',
            tags: ['reporting', 'framework', 'systematic']
          }
        ]
      }
    ]
  },
  {
    id: 'visualization-vr',
    title: 'Visualization & VR',
    description: 'Immersive visualization and virtual reality applications',
    color: 'bg-orange-500',
    icon: '🥽',
    topics: [
      {
        id: 'immersive-visualization',
        title: 'Immersive Visualization',
        description: 'Creating compelling 3D visualizations and walkthroughs',
        content: [
          {
            id: 'immersive-wiki',
            title: 'Real-time Rendering for Architecture',
            type: 'wiki',
            description: 'Techniques for real-time architectural visualization',
            content: 'Advanced real-time rendering techniques for architectural visualization...',
            readTime: '18 min read',
            author: 'Dr. Rachel Morgan',
            publishedAt: '2024-01-14',
            tags: ['real-time', 'rendering', 'visualization']
          },
          {
            id: 'immersive-podcast',
            title: 'The Future of Architectural Visualization',
            type: 'podcast',
            description: 'Emerging trends in architectural visualization technology',
            content: 'Exploring the future of architectural visualization and emerging technologies...',
            duration: '47 min',
            author: 'Viz Future Podcast',
            publishedAt: '2024-01-19',
            tags: ['future', 'trends', 'technology']
          },
          {
            id: 'immersive-video',
            title: 'Unreal Engine for Architecture',
            type: 'video',
            description: 'Using Unreal Engine for architectural visualization',
            content: 'Complete guide to using Unreal Engine for stunning architectural visualizations...',
            duration: '52 min',
            author: 'Arch Viz Academy',
            publishedAt: '2024-01-24',
            tags: ['unreal', 'engine', 'tutorial']
          },
          {
            id: 'immersive-guide',
            title: 'Lighting Design for Architectural Visualization',
            type: 'guide',
            description: 'Best practices for lighting in architectural renders',
            content: 'Essential lighting techniques for creating compelling architectural visualizations...',
            readTime: '12 min read',
            author: 'Lighting Design Studio',
            publishedAt: '2024-01-29',
            tags: ['lighting', 'design', 'rendering']
          }
        ]
      },
      {
        id: 'vr-experiences',
        title: 'VR Experiences',
        description: 'Virtual reality applications for architecture and construction',
        content: [
          {
            id: 'vr-wiki',
            title: 'VR for Design Review and Collaboration',
            type: 'wiki',
            description: 'Using VR for effective design review processes',
            content: 'Implementing VR technologies for enhanced design review and collaboration...',
            readTime: '15 min read',
            author: 'VR Design Lab',
            publishedAt: '2024-02-03',
            tags: ['vr', 'design-review', 'collaboration']
          },
          {
            id: 'vr-podcast',
            title: 'VR in Construction Training',
            type: 'podcast',
            description: 'Virtual reality applications in construction safety training',
            content: 'How VR is transforming construction safety training and education...',
            duration: '41 min',
            author: 'Construction Tech Talk',
            publishedAt: '2024-02-08',
            tags: ['construction', 'training', 'safety']
          },
          {
            id: 'vr-video',
            title: 'Building VR Experiences with Unity',
            type: 'video',
            description: 'Creating architectural VR experiences using Unity',
            content: 'Step-by-step guide to creating immersive architectural VR experiences...',
            duration: '49 min',
            author: 'Unity for Architecture',
            publishedAt: '2024-02-13',
            tags: ['unity', 'development', 'immersive']
          },
          {
            id: 'vr-guide',
            title: 'VR Hardware Selection Guide',
            type: 'guide',
            description: 'Choosing the right VR hardware for architectural applications',
            content: 'Comprehensive guide to selecting VR hardware for architectural workflows...',
            readTime: '11 min read',
            author: 'VR Hardware Review',
            publishedAt: '2024-02-18',
            tags: ['hardware', 'selection', 'comparison']
          }
        ]
      },
      {
        id: 'ar-applications',
        title: 'AR Applications',
        description: 'Augmented reality for construction and facility management',
        content: [
          {
            id: 'ar-wiki',
            title: 'AR for On-site Construction Guidance',
            type: 'wiki',
            description: 'Augmented reality applications in construction workflows',
            content: 'Implementing AR technologies for on-site construction guidance and quality control...',
            readTime: '17 min read',
            author: 'AR Construction Institute',
            publishedAt: '2024-02-23',
            tags: ['ar', 'construction', 'guidance']
          },
          {
            id: 'ar-podcast',
            title: 'Mixed Reality in Facility Management',
            type: 'podcast',
            description: 'Mixed reality applications for building operations',
            content: 'Exploring mixed reality solutions for facility management and maintenance...',
            duration: '44 min',
            author: 'Mixed Reality FM',
            publishedAt: '2024-02-28',
            tags: ['mixed-reality', 'facility', 'maintenance']
          },
          {
            id: 'ar-video',
            title: 'HoloLens for Building Information',
            type: 'video',
            description: 'Using Microsoft HoloLens for building data visualization',
            content: 'Practical applications of HoloLens for visualizing building information and systems...',
            duration: '36 min',
            author: 'Holographic Buildings',
            publishedAt: '2024-03-04',
            tags: ['hololens', 'microsoft', 'systems']
          },
          {
            id: 'ar-guide',
            title: 'AR Development for Architecture',
            type: 'guide',
            description: 'Getting started with AR development for architectural applications',
            content: 'Beginner-friendly guide to developing AR applications for architecture...',
            readTime: '14 min read',
            author: 'AR Development Team',
            publishedAt: '2024-03-09',
            tags: ['development', 'beginner', 'applications']
          }
        ]
      },
      {
        id: 'data-visualization',
        title: 'Data Visualization',
        description: 'Visual representation of building and sensor data',
        content: [
          {
            id: 'dataviz-wiki',
            title: 'Spatial Data Visualization Techniques',
            type: 'wiki',
            description: 'Advanced techniques for visualizing spatial building data',
            content: 'Comprehensive guide to spatial data visualization for building analytics...',
            readTime: '16 min read',
            author: 'Spatial Viz Lab',
            publishedAt: '2024-03-13',
            tags: ['spatial', 'techniques', 'analytics']
          },
          {
            id: 'dataviz-podcast',
            title: 'Interactive Building Dashboards',
            type: 'podcast',
            description: 'Creating engaging interactive dashboards for building data',
            content: 'Best practices for creating interactive and engaging building data dashboards...',
            duration: '40 min',
            author: 'Dashboard Design Weekly',
            publishedAt: '2024-03-18',
            tags: ['interactive', 'dashboards', 'engaging']
          },
          {
            id: 'dataviz-video',
            title: 'D3.js for Building Data Visualization',
            type: 'video',
            description: 'Using D3.js for custom building data visualizations',
            content: 'Learn to create custom building data visualizations using D3.js library...',
            duration: '45 min',
            author: 'D3 for Buildings',
            publishedAt: '2024-03-23',
            tags: ['d3js', 'custom', 'library']
          },
          {
            id: 'dataviz-guide',
            title: 'Color Theory for Data Visualization',
            type: 'guide',
            description: 'Effective color schemes for building data visualization',
            content: 'Guide to choosing effective color schemes for building data visualization...',
            readTime: '8 min read',
            author: 'Color Design Institute',
            publishedAt: '2024-03-28',
            tags: ['color', 'schemes', 'effective']
          }
        ]
      }
    ]
  }
];